apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: springboot-demo-service
  name: springboot-demo-service
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: springboot-demo-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: springboot-demo-service
    spec:
      containers:
        - image: >-
            registry-intl-vpc.ap-southeast-3.aliyuncs.com/techmeet/springboot-demo-service:1.0
          imagePullPolicy: Always
          name: springboot-demo-service
          ports:
            - containerPort: 8080
              name: http-8080
              protocol: TCP
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/localtime
              name: volume-localtime
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: techmeet-container-registry-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - hostPath:
            path: /etc/localtime
            type: ''
          name: volume-localtime
